onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /run_npu_simple/layer0/write_w
add wave -noupdate -radix unsigned /run_npu_simple/layer0/write_h
add wave -noupdate /run_npu_simple/layer0/data_in
add wave -noupdate /run_npu_simple/layer0/en_in
add wave -noupdate /run_npu_simple/layer0/readwg
add wave -noupdate /run_npu_simple/layer0/readhg
add wave -noupdate /run_npu_simple/layer0/en_read
add wave -noupdate /run_npu_simple/layer0/en_bias
add wave -noupdate /run_npu_simple/layer0/en_pe
add wave -noupdate /run_npu_simple/layer0/step
add wave -noupdate /run_npu_simple/layer0/out
add wave -noupdate /run_npu_simple/layer0/out_en
add wave -noupdate /run_npu_simple/layer0/clk
add wave -noupdate /run_npu_simple/layer0/i
add wave -noupdate /run_npu_simple/layer0/j
add wave -noupdate /run_npu_simple/layer0/k
add wave -noupdate /run_npu_simple/layer0/l
add wave -noupdate /run_npu_simple/layer0/w
add wave -noupdate /run_npu_simple/layer0/h
add wave -noupdate /run_npu_simple/layer0/s
add wave -noupdate /run_npu_simple/layer0/i_d
add wave -noupdate /run_npu_simple/layer0/i_2d
add wave -noupdate /run_npu_simple/layer0/i_3d
add wave -noupdate /run_npu_simple/layer0/i_4d
add wave -noupdate /run_npu_simple/layer0/i_5d
add wave -noupdate /run_npu_simple/layer0/i_6d
add wave -noupdate /run_npu_simple/layer0/i_7d
add wave -noupdate /run_npu_simple/layer0/j_d
add wave -noupdate /run_npu_simple/layer0/j_2d
add wave -noupdate /run_npu_simple/layer0/j_3d
add wave -noupdate /run_npu_simple/layer0/j_4d
add wave -noupdate /run_npu_simple/layer0/j_5d
add wave -noupdate /run_npu_simple/layer0/j_6d
add wave -noupdate /run_npu_simple/layer0/j_7d
add wave -noupdate /run_npu_simple/layer0/k_d
add wave -noupdate /run_npu_simple/layer0/k_2d
add wave -noupdate /run_npu_simple/layer0/k_3d
add wave -noupdate /run_npu_simple/layer0/k_4d
add wave -noupdate /run_npu_simple/layer0/k_5d
add wave -noupdate /run_npu_simple/layer0/k_6d
add wave -noupdate /run_npu_simple/layer0/k_7d
add wave -noupdate /run_npu_simple/layer0/f0
add wave -noupdate /run_npu_simple/layer0/f1
add wave -noupdate /run_npu_simple/layer0/f2
add wave -noupdate /run_npu_simple/layer0/f3
add wave -noupdate /run_npu_simple/layer0/f4
add wave -noupdate /run_npu_simple/layer0/f5
add wave -noupdate /run_npu_simple/layer0/f6
add wave -noupdate /run_npu_simple/layer0/f7
add wave -noupdate /run_npu_simple/layer0/fw
add wave -noupdate /run_npu_simple/layer0/fh
add wave -noupdate /run_npu_simple/layer0/readw
add wave -noupdate /run_npu_simple/layer0/readh
add wave -noupdate /run_npu_simple/layer0/data_in_ck
add wave -noupdate /run_npu_simple/layer0/data_in_w
add wave -noupdate /run_npu_simple/layer0/data_in_h
add wave -noupdate /run_npu_simple/layer0/ck_last_k0
add wave -noupdate /run_npu_simple/layer0/data_in_first
add wave -noupdate /run_npu_simple/layer0/enable_write_reading
add wave -noupdate /run_npu_simple/layer0/rightest
add wave -noupdate /run_npu_simple/layer0/pre_rightest
add wave -noupdate /run_npu_simple/layer0/start_save
add wave -noupdate -expand -subitemconfig {{/run_npu_simple/layer0/out_save[0]} {-childformat {{{/run_npu_simple/layer0/out_save[0][0]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][1]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][2]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][3]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][4]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][5]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][6]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][7]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][8]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][9]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][10]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][11]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][12]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][13]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][14]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][15]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][16]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][17]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][18]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][19]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][20]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][21]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][22]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][23]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][24]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][25]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][26]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][27]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][28]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][29]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][30]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][31]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][32]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][33]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][34]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][35]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][36]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][37]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][38]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][39]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][40]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][41]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][42]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][43]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][44]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][45]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][46]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][47]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][48]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][49]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][50]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][51]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][52]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][53]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][54]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][55]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][56]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][57]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][58]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][59]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][60]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][61]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][62]} -radix decimal} {{/run_npu_simple/layer0/out_save[0][63]} -radix decimal}} -expand} {/run_npu_simple/layer0/out_save[0][0]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][1]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][2]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][3]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][4]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][5]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][6]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][7]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][8]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][9]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][10]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][11]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][12]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][13]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][14]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][15]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][16]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][17]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][18]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][19]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][20]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][21]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][22]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][23]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][24]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][25]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][26]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][27]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][28]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][29]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][30]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][31]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][32]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][33]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][34]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][35]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][36]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][37]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][38]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][39]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][40]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][41]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][42]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][43]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][44]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][45]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][46]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][47]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][48]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][49]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][50]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][51]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][52]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][53]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][54]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][55]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][56]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][57]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][58]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][59]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][60]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][61]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][62]} {-radix decimal} {/run_npu_simple/layer0/out_save[0][63]} {-radix decimal}} /run_npu_simple/layer0/out_save
add wave -noupdate /run_npu_simple/npu/write_w
add wave -noupdate /run_npu_simple/npu/write_h
add wave -noupdate /run_npu_simple/npu/readi_w
add wave -noupdate /run_npu_simple/npu/readi_h
add wave -noupdate /run_npu_simple/npu/data_in
add wave -noupdate /run_npu_simple/npu/en_in
add wave -noupdate /run_npu_simple/npu/en_read
add wave -noupdate /run_npu_simple/npu/en_bias
add wave -noupdate /run_npu_simple/npu/step
add wave -noupdate /run_npu_simple/npu/en_pe
add wave -noupdate /run_npu_simple/npu/step_p
add wave -noupdate /run_npu_simple/npu/bound_level
add wave -noupdate /run_npu_simple/npu/en_relu
add wave -noupdate /run_npu_simple/npu/en_mp
add wave -noupdate /run_npu_simple/npu/clk
add wave -noupdate /run_npu_simple/npu/reset
add wave -noupdate /run_npu_simple/npu/out
add wave -noupdate /run_npu_simple/npu/out_en
add wave -noupdate /run_npu_simple/npu/fmaps
add wave -noupdate /run_npu_simple/npu/fmap
add wave -noupdate /run_npu_simple/npu/weight
add wave -noupdate /run_npu_simple/npu/biases
add wave -noupdate /run_npu_simple/npu/biasp
add wave -noupdate /run_npu_simple/npu/step_d
add wave -noupdate /run_npu_simple/npu/bound_level_d
add wave -noupdate /run_npu_simple/npu/en_pe_d
add wave -noupdate /run_npu_simple/npu/data_in_each
add wave -noupdate /run_npu_simple/npu/data_mc
add wave -noupdate -radix decimal -childformat {{{/run_npu_simple/npu/data_cp[0]} -radix decimal} {{/run_npu_simple/npu/data_cp[1]} -radix decimal} {{/run_npu_simple/npu/data_cp[2]} -radix decimal} {{/run_npu_simple/npu/data_cp[3]} -radix decimal} {{/run_npu_simple/npu/data_cp[4]} -radix decimal} {{/run_npu_simple/npu/data_cp[5]} -radix decimal} {{/run_npu_simple/npu/data_cp[6]} -radix decimal} {{/run_npu_simple/npu/data_cp[7]} -radix decimal} {{/run_npu_simple/npu/data_cp[8]} -radix decimal}} -expand -subitemconfig {{/run_npu_simple/npu/data_cp[0]} {-radix decimal} {/run_npu_simple/npu/data_cp[1]} {-radix decimal} {/run_npu_simple/npu/data_cp[2]} {-radix decimal} {/run_npu_simple/npu/data_cp[3]} {-radix decimal} {/run_npu_simple/npu/data_cp[4]} {-radix decimal} {/run_npu_simple/npu/data_cp[5]} {-radix decimal} {/run_npu_simple/npu/data_cp[6]} {-radix decimal} {/run_npu_simple/npu/data_cp[7]} {-radix decimal} {/run_npu_simple/npu/data_cp[8]} {-radix decimal}} /run_npu_simple/npu/data_cp
add wave -noupdate /run_npu_simple/npu/weight_group_cp
add wave -noupdate /run_npu_simple/npu/bias_cp
add wave -noupdate /run_npu_simple/npu/readw
add wave -noupdate /run_npu_simple/npu/readh
add wave -noupdate -childformat {{{/run_npu_simple/npu/memory/mem[0]} -radix decimal} {{/run_npu_simple/npu/memory/mem[1]} -radix decimal} {{/run_npu_simple/npu/memory/mem[2]} -radix decimal} {{/run_npu_simple/npu/memory/mem[3]} -radix decimal} {{/run_npu_simple/npu/memory/mem[4]} -radix decimal} {{/run_npu_simple/npu/memory/mem[5]} -radix decimal} {{/run_npu_simple/npu/memory/mem[6]} -radix decimal} {{/run_npu_simple/npu/memory/mem[7]} -radix decimal} {{/run_npu_simple/npu/memory/mem[8]} -radix decimal} {{/run_npu_simple/npu/memory/mem[9]} -radix decimal} {{/run_npu_simple/npu/memory/mem[10]} -radix decimal} {{/run_npu_simple/npu/memory/mem[11]} -radix decimal} {{/run_npu_simple/npu/memory/mem[12]} -radix decimal} {{/run_npu_simple/npu/memory/mem[13]} -radix decimal} {{/run_npu_simple/npu/memory/mem[14]} -radix decimal} {{/run_npu_simple/npu/memory/mem[15]} -radix decimal} {{/run_npu_simple/npu/memory/mem[16]} -radix decimal} {{/run_npu_simple/npu/memory/mem[17]} -radix decimal} {{/run_npu_simple/npu/memory/mem[18]} -radix decimal} {{/run_npu_simple/npu/memory/mem[19]} -radix decimal} {{/run_npu_simple/npu/memory/mem[20]} -radix decimal} {{/run_npu_simple/npu/memory/mem[21]} -radix decimal} {{/run_npu_simple/npu/memory/mem[22]} -radix decimal} {{/run_npu_simple/npu/memory/mem[23]} -radix decimal} {{/run_npu_simple/npu/memory/mem[24]} -radix decimal} {{/run_npu_simple/npu/memory/mem[25]} -radix decimal} {{/run_npu_simple/npu/memory/mem[26]} -radix decimal} {{/run_npu_simple/npu/memory/mem[27]} -radix decimal} {{/run_npu_simple/npu/memory/mem[28]} -radix decimal} {{/run_npu_simple/npu/memory/mem[29]} -radix decimal} {{/run_npu_simple/npu/memory/mem[30]} -radix decimal} {{/run_npu_simple/npu/memory/mem[31]} -radix decimal} {{/run_npu_simple/npu/memory/mem[32]} -radix decimal} {{/run_npu_simple/npu/memory/mem[33]} -radix decimal} {{/run_npu_simple/npu/memory/mem[34]} -radix decimal} {{/run_npu_simple/npu/memory/mem[35]} -radix decimal} {{/run_npu_simple/npu/memory/mem[36]} -radix decimal} {{/run_npu_simple/npu/memory/mem[37]} -radix decimal} {{/run_npu_simple/npu/memory/mem[38]} -radix decimal} {{/run_npu_simple/npu/memory/mem[39]} -radix decimal} {{/run_npu_simple/npu/memory/mem[40]} -radix decimal} {{/run_npu_simple/npu/memory/mem[41]} -radix decimal} {{/run_npu_simple/npu/memory/mem[42]} -radix decimal} {{/run_npu_simple/npu/memory/mem[43]} -radix decimal} {{/run_npu_simple/npu/memory/mem[44]} -radix decimal} {{/run_npu_simple/npu/memory/mem[45]} -radix decimal} {{/run_npu_simple/npu/memory/mem[46]} -radix decimal} {{/run_npu_simple/npu/memory/mem[47]} -radix decimal} {{/run_npu_simple/npu/memory/mem[48]} -radix decimal} {{/run_npu_simple/npu/memory/mem[49]} -radix decimal} {{/run_npu_simple/npu/memory/mem[50]} -radix decimal} {{/run_npu_simple/npu/memory/mem[51]} -radix decimal} {{/run_npu_simple/npu/memory/mem[52]} -radix decimal} {{/run_npu_simple/npu/memory/mem[53]} -radix decimal} {{/run_npu_simple/npu/memory/mem[54]} -radix decimal} {{/run_npu_simple/npu/memory/mem[55]} -radix decimal} {{/run_npu_simple/npu/memory/mem[56]} -radix decimal} {{/run_npu_simple/npu/memory/mem[57]} -radix decimal} {{/run_npu_simple/npu/memory/mem[58]} -radix decimal} {{/run_npu_simple/npu/memory/mem[59]} -radix decimal} {{/run_npu_simple/npu/memory/mem[60]} -radix decimal} {{/run_npu_simple/npu/memory/mem[61]} -radix decimal} {{/run_npu_simple/npu/memory/mem[62]} -radix decimal} {{/run_npu_simple/npu/memory/mem[63]} -radix decimal} {{/run_npu_simple/npu/memory/mem[64]} -radix decimal} {{/run_npu_simple/npu/memory/mem[65]} -radix decimal} {{/run_npu_simple/npu/memory/mem[66]} -radix decimal} {{/run_npu_simple/npu/memory/mem[67]} -radix decimal} {{/run_npu_simple/npu/memory/mem[68]} -radix decimal} {{/run_npu_simple/npu/memory/mem[69]} -radix decimal} {{/run_npu_simple/npu/memory/mem[70]} -radix decimal} {{/run_npu_simple/npu/memory/mem[71]} -radix decimal} {{/run_npu_simple/npu/memory/mem[72]} -radix decimal} {{/run_npu_simple/npu/memory/mem[73]} -radix decimal} {{/run_npu_simple/npu/memory/mem[74]} -radix decimal} {{/run_npu_simple/npu/memory/mem[75]} -radix decimal} {{/run_npu_simple/npu/memory/mem[76]} -radix decimal} {{/run_npu_simple/npu/memory/mem[77]} -radix decimal} {{/run_npu_simple/npu/memory/mem[78]} -radix decimal} {{/run_npu_simple/npu/memory/mem[79]} -radix decimal} {{/run_npu_simple/npu/memory/mem[80]} -radix decimal} {{/run_npu_simple/npu/memory/mem[81]} -radix decimal}} -expand -subitemconfig {{/run_npu_simple/npu/memory/mem[0]} {-radix decimal} {/run_npu_simple/npu/memory/mem[1]} {-radix decimal} {/run_npu_simple/npu/memory/mem[2]} {-radix decimal} {/run_npu_simple/npu/memory/mem[3]} {-radix decimal} {/run_npu_simple/npu/memory/mem[4]} {-radix decimal} {/run_npu_simple/npu/memory/mem[5]} {-radix decimal} {/run_npu_simple/npu/memory/mem[6]} {-radix decimal} {/run_npu_simple/npu/memory/mem[7]} {-radix decimal} {/run_npu_simple/npu/memory/mem[8]} {-radix decimal} {/run_npu_simple/npu/memory/mem[9]} {-radix decimal} {/run_npu_simple/npu/memory/mem[10]} {-radix decimal} {/run_npu_simple/npu/memory/mem[11]} {-radix decimal} {/run_npu_simple/npu/memory/mem[12]} {-radix decimal} {/run_npu_simple/npu/memory/mem[13]} {-radix decimal} {/run_npu_simple/npu/memory/mem[14]} {-radix decimal} {/run_npu_simple/npu/memory/mem[15]} {-radix decimal} {/run_npu_simple/npu/memory/mem[16]} {-radix decimal} {/run_npu_simple/npu/memory/mem[17]} {-radix decimal} {/run_npu_simple/npu/memory/mem[18]} {-radix decimal} {/run_npu_simple/npu/memory/mem[19]} {-radix decimal} {/run_npu_simple/npu/memory/mem[20]} {-radix decimal} {/run_npu_simple/npu/memory/mem[21]} {-radix decimal} {/run_npu_simple/npu/memory/mem[22]} {-radix decimal} {/run_npu_simple/npu/memory/mem[23]} {-radix decimal} {/run_npu_simple/npu/memory/mem[24]} {-radix decimal} {/run_npu_simple/npu/memory/mem[25]} {-radix decimal} {/run_npu_simple/npu/memory/mem[26]} {-radix decimal} {/run_npu_simple/npu/memory/mem[27]} {-radix decimal} {/run_npu_simple/npu/memory/mem[28]} {-radix decimal} {/run_npu_simple/npu/memory/mem[29]} {-radix decimal} {/run_npu_simple/npu/memory/mem[30]} {-radix decimal} {/run_npu_simple/npu/memory/mem[31]} {-radix decimal} {/run_npu_simple/npu/memory/mem[32]} {-radix decimal} {/run_npu_simple/npu/memory/mem[33]} {-radix decimal} {/run_npu_simple/npu/memory/mem[34]} {-radix decimal} {/run_npu_simple/npu/memory/mem[35]} {-radix decimal} {/run_npu_simple/npu/memory/mem[36]} {-radix decimal} {/run_npu_simple/npu/memory/mem[37]} {-radix decimal} {/run_npu_simple/npu/memory/mem[38]} {-radix decimal} {/run_npu_simple/npu/memory/mem[39]} {-radix decimal} {/run_npu_simple/npu/memory/mem[40]} {-radix decimal} {/run_npu_simple/npu/memory/mem[41]} {-radix decimal} {/run_npu_simple/npu/memory/mem[42]} {-radix decimal} {/run_npu_simple/npu/memory/mem[43]} {-radix decimal} {/run_npu_simple/npu/memory/mem[44]} {-radix decimal} {/run_npu_simple/npu/memory/mem[45]} {-radix decimal} {/run_npu_simple/npu/memory/mem[46]} {-radix decimal} {/run_npu_simple/npu/memory/mem[47]} {-radix decimal} {/run_npu_simple/npu/memory/mem[48]} {-radix decimal} {/run_npu_simple/npu/memory/mem[49]} {-radix decimal} {/run_npu_simple/npu/memory/mem[50]} {-radix decimal} {/run_npu_simple/npu/memory/mem[51]} {-radix decimal} {/run_npu_simple/npu/memory/mem[52]} {-radix decimal} {/run_npu_simple/npu/memory/mem[53]} {-radix decimal} {/run_npu_simple/npu/memory/mem[54]} {-radix decimal} {/run_npu_simple/npu/memory/mem[55]} {-radix decimal} {/run_npu_simple/npu/memory/mem[56]} {-radix decimal} {/run_npu_simple/npu/memory/mem[57]} {-radix decimal} {/run_npu_simple/npu/memory/mem[58]} {-radix decimal} {/run_npu_simple/npu/memory/mem[59]} {-radix decimal} {/run_npu_simple/npu/memory/mem[60]} {-radix decimal} {/run_npu_simple/npu/memory/mem[61]} {-radix decimal} {/run_npu_simple/npu/memory/mem[62]} {-radix decimal} {/run_npu_simple/npu/memory/mem[63]} {-radix decimal} {/run_npu_simple/npu/memory/mem[64]} {-radix decimal} {/run_npu_simple/npu/memory/mem[65]} {-radix decimal} {/run_npu_simple/npu/memory/mem[66]} {-radix decimal} {/run_npu_simple/npu/memory/mem[67]} {-radix decimal} {/run_npu_simple/npu/memory/mem[68]} {-radix decimal} {/run_npu_simple/npu/memory/mem[69]} {-radix decimal} {/run_npu_simple/npu/memory/mem[70]} {-radix decimal} {/run_npu_simple/npu/memory/mem[71]} {-radix decimal} {/run_npu_simple/npu/memory/mem[72]} {-radix decimal} {/run_npu_simple/npu/memory/mem[73]} {-radix decimal} {/run_npu_simple/npu/memory/mem[74]} {-radix decimal} {/run_npu_simple/npu/memory/mem[75]} {-radix decimal} {/run_npu_simple/npu/memory/mem[76]} {-radix decimal} {/run_npu_simple/npu/memory/mem[77]} {-radix decimal} {/run_npu_simple/npu/memory/mem[78]} {-radix decimal} {/run_npu_simple/npu/memory/mem[79]} {-radix decimal} {/run_npu_simple/npu/memory/mem[80]} {-radix decimal} {/run_npu_simple/npu/memory/mem[81]} {-radix decimal}} /run_npu_simple/npu/memory/mem
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/in}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/weight}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/bias}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/out}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/out_en}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/clk}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/reset}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/en}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/en_d}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/bound_level}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/bound_level_d}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/step}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/step_d}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/pre_output}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/addout}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/b_out}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/oxor}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/chk_over}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/pre_output_b}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/p_step}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/mux_f_s}
add wave -noupdate {/run_npu_simple/npu/arithmetic/generate_ac[7]/ac/P0/out_ck_en}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5751150 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 361
configure wave -valuecolwidth 173
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {5678710 ps} {5786150 ps}
